# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from deepagents.backends import sandbox_io_pb2 as sandbox__io__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_io_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxIORouterStub(object):
    """--- Service Definition ---

    gRPC service for Sandbox I/O operations
    Provides fast, low-latency file operations bypassing shell commands
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFile = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/ReadFile',
                request_serializer=sandbox__io__pb2.ReadRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/WriteFile',
                request_serializer=sandbox__io__pb2.WriteRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.WriteResult.FromString,
                _registered_method=True)
        self.EditFile = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/EditFile',
                request_serializer=sandbox__io__pb2.EditRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.EditResult.FromString,
                _registered_method=True)
        self.ListInfo = channel.unary_stream(
                '/deepagents.sandbox.SandboxIORouter/ListInfo',
                request_serializer=sandbox__io__pb2.ListRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.FileInfo.FromString,
                _registered_method=True)
        self.GrepRaw = channel.unary_stream(
                '/deepagents.sandbox.SandboxIORouter/GrepRaw',
                request_serializer=sandbox__io__pb2.GrepRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.GrepMatch.FromString,
                _registered_method=True)
        self.GlobInfo = channel.unary_stream(
                '/deepagents.sandbox.SandboxIORouter/GlobInfo',
                request_serializer=sandbox__io__pb2.GlobRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.FileInfo.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/Execute',
                request_serializer=sandbox__io__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.UploadFiles = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/UploadFiles',
                request_serializer=sandbox__io__pb2.UploadRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.DownloadFiles = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/DownloadFiles',
                request_serializer=sandbox__io__pb2.DownloadRequest.SerializeToString,
                response_deserializer=sandbox__io__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.GetId = channel.unary_unary(
                '/deepagents.sandbox.SandboxIORouter/GetId',
                request_serializer=sandbox__io__pb2.Empty.SerializeToString,
                response_deserializer=sandbox__io__pb2.IdResponse.FromString,
                _registered_method=True)


class SandboxIORouterServicer(object):
    """--- Service Definition ---

    gRPC service for Sandbox I/O operations
    Provides fast, low-latency file operations bypassing shell commands
    """

    def ReadFile(self, request, context):
        """Read file content with optional offset and limit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Write content to a new file (error if exists unless overwrite=true)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditFile(self, request, context):
        """Edit file by replacing string occurrences
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInfo(self, request, context):
        """List directory contents, streaming for large directories
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrepRaw(self, request, context):
        """Search for pattern in files, streaming results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobInfo(self, request, context):
        """Find files matching glob pattern, streaming results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute a shell command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFiles(self, request, context):
        """Upload multiple files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFiles(self, request, context):
        """Download multiple files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetId(self, request, context):
        """Get the sandbox ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxIORouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=sandbox__io__pb2.ReadRequest.FromString,
                    response_serializer=sandbox__io__pb2.ReadResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=sandbox__io__pb2.WriteRequest.FromString,
                    response_serializer=sandbox__io__pb2.WriteResult.SerializeToString,
            ),
            'EditFile': grpc.unary_unary_rpc_method_handler(
                    servicer.EditFile,
                    request_deserializer=sandbox__io__pb2.EditRequest.FromString,
                    response_serializer=sandbox__io__pb2.EditResult.SerializeToString,
            ),
            'ListInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.ListInfo,
                    request_deserializer=sandbox__io__pb2.ListRequest.FromString,
                    response_serializer=sandbox__io__pb2.FileInfo.SerializeToString,
            ),
            'GrepRaw': grpc.unary_stream_rpc_method_handler(
                    servicer.GrepRaw,
                    request_deserializer=sandbox__io__pb2.GrepRequest.FromString,
                    response_serializer=sandbox__io__pb2.GrepMatch.SerializeToString,
            ),
            'GlobInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.GlobInfo,
                    request_deserializer=sandbox__io__pb2.GlobRequest.FromString,
                    response_serializer=sandbox__io__pb2.FileInfo.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=sandbox__io__pb2.ExecuteRequest.FromString,
                    response_serializer=sandbox__io__pb2.ExecuteResponse.SerializeToString,
            ),
            'UploadFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=sandbox__io__pb2.UploadRequest.FromString,
                    response_serializer=sandbox__io__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFiles,
                    request_deserializer=sandbox__io__pb2.DownloadRequest.FromString,
                    response_serializer=sandbox__io__pb2.DownloadResponse.SerializeToString,
            ),
            'GetId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetId,
                    request_deserializer=sandbox__io__pb2.Empty.FromString,
                    response_serializer=sandbox__io__pb2.IdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepagents.sandbox.SandboxIORouter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deepagents.sandbox.SandboxIORouter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxIORouter(object):
    """--- Service Definition ---

    gRPC service for Sandbox I/O operations
    Provides fast, low-latency file operations bypassing shell commands
    """

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/ReadFile',
            sandbox__io__pb2.ReadRequest.SerializeToString,
            sandbox__io__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/WriteFile',
            sandbox__io__pb2.WriteRequest.SerializeToString,
            sandbox__io__pb2.WriteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/EditFile',
            sandbox__io__pb2.EditRequest.SerializeToString,
            sandbox__io__pb2.EditResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/ListInfo',
            sandbox__io__pb2.ListRequest.SerializeToString,
            sandbox__io__pb2.FileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrepRaw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/GrepRaw',
            sandbox__io__pb2.GrepRequest.SerializeToString,
            sandbox__io__pb2.GrepMatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/GlobInfo',
            sandbox__io__pb2.GlobRequest.SerializeToString,
            sandbox__io__pb2.FileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/Execute',
            sandbox__io__pb2.ExecuteRequest.SerializeToString,
            sandbox__io__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/UploadFiles',
            sandbox__io__pb2.UploadRequest.SerializeToString,
            sandbox__io__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/DownloadFiles',
            sandbox__io__pb2.DownloadRequest.SerializeToString,
            sandbox__io__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepagents.sandbox.SandboxIORouter/GetId',
            sandbox__io__pb2.Empty.SerializeToString,
            sandbox__io__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
